// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVA0DWDNeYIsTm5IcwPVdIWJya6sTENU',
    appId: '1:435395318116:web:0ffe0621986607e5eb2a71',
    messagingSenderId: '435395318116',
    projectId: 'petadoption-b33b9',
    authDomain: 'petadoption-b33b9.firebaseapp.com',
    storageBucket: 'petadoption-b33b9.firebasestorage.app',
    measurementId: 'G-G2DJBYHBXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa9nrRNEm8upL2eUvygx1LU2AeQO6Hp2E',
    appId: '1:435395318116:android:2d7a42fdbae430bfeb2a71',
    messagingSenderId: '435395318116',
    projectId: 'petadoption-b33b9',
    storageBucket: 'petadoption-b33b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH7vi01j8i4isTc9TtMWUetfbM8Nd6wOg',
    appId: '1:435395318116:ios:7a8264a340ae7fdaeb2a71',
    messagingSenderId: '435395318116',
    projectId: 'petadoption-b33b9',
    storageBucket: 'petadoption-b33b9.firebasestorage.app',
    iosClientId: '435395318116-440945imbjdg5teabs8tp27v67svcajp.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdoptionMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH7vi01j8i4isTc9TtMWUetfbM8Nd6wOg',
    appId: '1:435395318116:ios:7a8264a340ae7fdaeb2a71',
    messagingSenderId: '435395318116',
    projectId: 'petadoption-b33b9',
    storageBucket: 'petadoption-b33b9.firebasestorage.app',
    iosClientId: '435395318116-440945imbjdg5teabs8tp27v67svcajp.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdoptionMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVA0DWDNeYIsTm5IcwPVdIWJya6sTENU',
    appId: '1:435395318116:web:31e4fe8cf80b4561eb2a71',
    messagingSenderId: '435395318116',
    projectId: 'petadoption-b33b9',
    authDomain: 'petadoption-b33b9.firebaseapp.com',
    storageBucket: 'petadoption-b33b9.firebasestorage.app',
    measurementId: 'G-D5SS957G38',
  );
}
